# Software Development Environments

## tl;dr

 * Integrated Development Environments (IDEs): we recommend you use one for software development ✔
 * Jupyter notebooks: great for tutorials and as a playground for getting familiar with code, but not great for software engineering 🚸
 * plain text editors: try to avoid, although sometimes you have to use on ⛔

## Integrated Development Environments (IDEs)

 * All-in-one that comes with many features to help to code
 * We think it is worth the (small) effort to learn to use one
 * The two leading IDEs for Python are VS Code and PyCharm
 * We will be demoing useful features in VS Code throughout the week
 * Demo:
    * VS Code workspace introduction
    * Autocomplete
    * Static error checking (linting)
    * Git integration
    * Extras: SSH integration, marketplace

## Jupyter Notebooks 

 * Combination of code cells and Markdown text cells make it useful for writing tutorials
 * Running/rerunning one cell at a time allows you to play around with the code/understand how it works
 * Useful for plotting, solving a problem (think of it as a document)
 * Output depends on order cells and run/rerun -> not good for repeatibility
 * Not designed for programming a software package

## Plain text editors

* The "old-school" editors (e.g., vim, emacs, nano, notepad++)
* We generally recommend you avoid doing large amounts of programing in them as the code is prone to bugs
* Sometimes inevitable in astronomy so it is good to learn a little bit of either vim or emacs
* You can use VS Code over ssh, so you should not need to use these very often!

# Object-Oriented and Functional Programming

## tl;dr

 * Object-oriented programming relies on the state of variables to determine the output
    * Good to keep track of something that is changing (e.g., the number of people in a Zoom meeting)
 * Functional programming relies solely on the inputs, which do not change, to determine the output
    * Good for math equations (e.g., computing the inverse of a matrix)
 * Typically, you will want a mix of both programming paradigms

## Object-Oriented Programming
 
![](../imgs/oo-meme.png)

In [20]:
# Object-Oriented Programming
import astropy.units as u

class FreeFallParticle(object):
    """
    Simulate a particle falling in due to Earth's gravity. Particle is stationary at first

    Args:
        height (float): a height in meters
        dt (float): timestep of the simulation in seconds
    """
    def __init__(self, height, dt=0.1):
        self.height = height * u.m
        self.velocity = 0 * u.m/u.s
        self.time = 0 * u.s
        self.dt = dt * u.s

    def timestep(self):
        """
        Step forward in time. Return the current height of the object

        Returns:
            curr_height (float): current height
        """
        # change the object's velocity
        self.velocity += -9.8 * u.m/u.s**2 * self.dt
        # cause it to fall a bit
        self.height += self.velocity * self.dt

        return self.height.value

ball = FreeFallParticle(1) # start out a 1 m above the ground
print(ball.time, ball.height)
for i in range(5):
    ball.timestep()
    print(ball.time, ball.height)


0.0 s 1.0 m
0.0 s 0.902 m
0.0 s 0.706 m
0.0 s 0.4119999999999999 m
0.0 s 0.01999999999999985 m
0.0 s -0.4700000000000002 m


## Object Oriented Programming
    
 * Depends on changing (mutable) state: `self.height`, `self.velocity`
 * Most things in the world change, so it makes sense to frame things in this way
 * What if you want to save the height and velocity of the object at each time step?

## Functional Programming

![](../imgs/fp-meme.png)

In [24]:
# Functional Programming Example. 

class Particle(object):
    """
    A particle with a given height and vertical instantaneous velocity

    Args:
        height (float): height of the object currenly in meters
        velocity (float): velocity of the object in meters. Default is 0 (at rest)
    """
    def __init__(self, height, velocity=0):
        self.height = height * u.m
        self.velocity = velocity * u.m/u.s

def freefall_timestep(thing, dt=0.1):
    """
    Simulate free fall of the particle for a small time step

    Args:
        thing (Particle): the current position and velocity of the particle
        dt (float): optional float that specifies the timestep in seconds

    Returns:
        new_thing (Particle): the updated position and velocity of the particle
    """
    dt_units = dt * u.s
    new_velocity = thing.velocity + -9.8 * u.m / u.s**2 * dt_units
    new_height = thing.height + new_velocity * dt_units

    new_thing = Particle(new_height.value, new_velocity.value)
    return new_thing


ball = Particle(1) # start a ball at 1 m
ball_states = [ball]
print(0 * u.s, ball.height)
dt = 0.1
time = 0

for i in range(5):
    new_ball = freefall_timestep(ball_states[-1], dt)
    ball_states = ball_states + [new_ball,]
    time += dt
    print(time * u.s, new_ball.height)



0.0 s 1.0 m
0.1 s 0.902 m
0.2 s 0.706 m
0.30000000000000004 s 0.4119999999999999 m
0.4 s 0.01999999999999985 m
0.5 s -0.4700000000000002 m


## Functional Programming

 * Functions outputs depend solely on the inputs
 * Functional programming != no objects. Objects however are static data structures.
 * In functional programming, each object does not change. You need to create a new object 
 * Useful for math problems, physics equations, unit conversions
    * `import astropy.units as u; u.m.to(u.nm)`

# Object Oriented vs Functional Programming

 * Object oriented programming is good when things change (e.g., the position of a planet, the current image being analyzed)
 * Functional programming is good to deterministic things (e.g., math equations, making sure you do not accidentally apply the same application twice)
 * Python supports both, and most packages implement both
 * Don't overthink it! 

# Activity

Implement the function to get all of the previous heights and their corresponding times the free falling object was at. For example, if the object was at `height = 1` at `time = 0`, `height = 0.902` at `t = 0.1`, and `height = 0.706` at `t = 0.2`, the function should return `[1, 0.902, 0.706]` for the heights and `[0, 0.1, 0.2]` for the corresponding times. Choose to implement it either in the object oriented or functional framework we provided. If you have time, try the other one too!
